#!/bin/bash

##### SET ARCHITECTURE [x86 or ARM] #####
SYSARCH="x86"
#########################################

if [ $# -ne 2 ]; then
	echo "usage: ./xkdb_builder [xinu_dir] [xkdb_dir]"
	exit 1
fi

if [ "$SYSARCH" != "x86" ] && [ "$SYSARCH" != "ARM" ]; then
	echo "Incorrect Architecture! Must be either x86 or ARM!"
	exit 1
fi

XINU_DIR=$1
XKDB_DIR=$2

if [ "$SYSARCH" == "x86" ]; then
	cp $XKDB_DIR/stub/i386-stub.c $XINU_DIR/system/i386-stub.c	
elif [ "$SYSARCH" == "ARM" ]; then
	cp $XKDB_DIR/stub/arm-stub.c $XINU_DIR/system/arm-stub.c
fi


